### Ruby-Challenge API Documentation
##### Product Specifications
The API have the following features:
* Create an User
* Confirm User with email
* Login User
* Create an TODO List
* Change mode of TODO list (pending, initiated, done)
* Delete TODO List
* Create an Item
* Change mode of Item (pending, read, executed, archived)
* Delete Item
* List items ans lists according to their status
* Pagination


##### Staging: http://ruby-challenge-staging.herokuapp.com/
##### Production: http://ruby-challenge-production.herokuapp.com/
##### DEV Environment: http://localhost:3000/

Change MODE constant to the environment who will receive the request

In [1]:
## CHANGE CONSTANT TO YOUR ENV MODE
MODE = 'dev'
# MODE = 'prod'
# MODE = 'stag'

## REQUIREMENTS
import requests
import json
import pandas as pd
import time


## CHECK ENV MODE AND DEFINE URL FOR REQUESTS
if MODE == 'dev':
    url = 'http://localhost:3000'
elif MODE == 'prod':
    url = 'https://ruby-challenge-production.herokuapp.com'
elif MODE == 'stag':
    url = 'https://ruby-challenge-staging.herokuapp.com'



## SOME METHODS TO HELP DEMONSTRATE

def post_items(token, todo_list_id, action, name):
    """
    Post items
    """
    auth_head_tag = {'Authorization':token}

    item_params = {'item[todo_list_id]': todo_list_id, 'item[action]': action,'item[name]': name}

    r = requests.post((url + '/api/items'), headers=auth_head_tag, params=item_params)

    return r.text


def mark_item_as_read(token, item_id):
    """
    Mark item as read
    """
    headers = {
        'Authorization': token
    }
    params = {
        'id': item_id
    }
    r = requests.get((url + '/api/view_item'), headers=headers, params=params)
    return r.text

def mark_item_as_executed(token, item_id):
    """
    Mark item as executed
    """
    headers = {
        'Authorization': token
    }
    params = {
        'id': item_id,
        'executed': 'true'
    }
    r = requests.get((url + '/api/view_item'), headers=headers, params=params)
    return r.text



def mark_item_as_archived(token, item_id):
    """
    Mark item as archived
    """
    headers = {
        'Authorization': token
    }
    params = {
        'id': item_id,
        'archived': 'true'
    }
    r = requests.get((url + '/api/view_item'), headers=headers, params=params)
    return r.text


def mark_todo_as_done(token, todo_list_id):
    """
    Mark todo as executed
    """
    headers = {
        'Authorization': token
    }
    params = {
        'id': todo_list_id,
        'done': 'true'
    }
    r = requests.get((url + '/api/view_todo_list/'), headers=headers, params=params)
    return r.text

#### GET / - returns the root page of the API ('http://localhost:3000')

In [2]:
## SEND REQUEST TO ENV URL
r = requests.get(url)

## HOLD JSON RESPONSE IN A VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON: ', json_response)

## PRINT RESPONSE INFO
# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)

## PRINT JSON RESPONSE AS DATA FRAME
pd.json_normalize(json_response)

              message
0  Welcome to the API

#### GET /users/sign_in - returns a message informing what information you need to sign in

In [3]:
## SEND REQUEST TO API USERS LOGIN
r = requests.get((url + '/api/users/login'))

## PRINT RESPONSE INFORMATIONS
# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON: ', json_response )

## PRINT RESPONSE IN DATA FRAME
pd.json_normalize(json_response)

                    message
0  Enter email and password

#### GET /users/sign_up - returns a message informing what you need to sign up

In [4]:
#  GET REQUEST API USERS SIGN UP
r = requests.get((url + '/api/users/sign_up'))

## PRINT RESPONSE INFORMATIONS
# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)

## HOLD JSON RESPONSE IN A VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
#print('JSON: ', json_response)

## PRINT JSON RESPONSE IN DATA FRAME 
pd.json_normalize(json_response)

                              message
0  Enter email, username and password

#### POST /users - creates a new user

After the user signs up, he/she will receive an email with a link to confirm his/her email address


So the user must confirm his/her email address before he/she can login

In [5]:
#HOLD SIGN UP PARAMS
sign_up_params = {'user[email]': 'mail@mail.com', 'user[username]': 'username', 'user[password]': 'password'}

## MAKE POST REQUEST IN API USERS
r = requests.post((url + '/api/users'), params=sign_up_params)


## PRINT ALL RESPONSE INFORMATION
# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)


## HOLD JSON RESPONSE IN A VARIABLE
json_response = json.loads(r.text)

## SHOW JSON RESPONSE
# print('JSON: ', json_response)


##  error may raise because of the email already exists
##  use this account to login
##  email: mail@mail.com
##  password: password


pd.json_normalize(json_response)

                                             message
0  You have successfully signed up, please activa...

#### POST /users/login - logs in a user

**Utilize login params - email, password to get authentication token**

**Utilize the authentication token to make requests to the API**

**The authentication token will expire after a certain period of time**

**If the authentication token expires, you will need to sign in again**

**To get working the authentication token, you will need to set it in the header of your request**

**headers = {'Authorization': TOKEN }**

In [6]:
## HOLD LOGIN PARAMS IN A VARIABLE
login_params = {'user[email]': 'mail@mail.com', 'user[password]': 'password'}

## SEND POST REQUEST TO API USERS LOGIN
r = requests.post((url + '/api/users/login'), params=login_params)

## PRINT ALL RESPONSE INFORMATION
# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

#HOLD JWT TOKEN IN VARIABLE
token = json_response['token']

## PRINT AUTHORIZATION TOKEN
# print('TOKEN: ', token)

## PRINT JSON RESPONSER AS DATA FRAME
pd.json_normalize(json_response)

,message,token
0,You have successfully logged in,eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjU0M...

##### **EXAMPLE OF A REQUEST WITH THE AUTHENTICATION TOKEN**


##### **GET TODO LIST - returns a list of all the TODO lists**


##### **DOCUMENTATION OF GET TODO LIST IS ON HIS OWN SECTION**

In [7]:
## HOLD AUTHORIZATION TOKEN HEADER
auth_head_tag = {'Authorization':token}

## SEND GET REQUEST WITH AUTHORIZATION TOKEN
r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON: ', json_response)

## HOLD STATUS CODE IN VARIABLE
status = r.status_code
## WHEN THE REQUEST IS SUCCESSFUL, THE STATUS CODE IS 200

## PRINT STATUS CODE
print('STATUS_CODE: ', status)

## PRITN JSON RESPONSE AS DATA FRAME
# pd.json_normalize(json_response)

STATUS_CODE:  200

#### POST /api/todo_lists - creates a new todo list
 
**ACCEPT PARAMS:**

    * title
    * description
    * action


**SETTED AUTOMATICALLY:**
    * user_id
    * mode
    * created_at
    * updated_at
    * items_count

DEFAULT VALUES:
    * mode = pending
    * items_count = 0
    * created_at = updated_at = current time
    * user_id = the user who created the list


**EXAMPLE PARAMS:**
    
        { "item": 
            { "title": "",
              "description": "",
              "action": "",
            }
        }

**URL PARAMS EXAMPLE:**
?item[title]=VALUE&item[description]=VALUE&item[action]=VALUE


**RETURN TODO LIST OBJECT IF CREATED**

In [8]:
## CREATED BOOLEAN TO CHECK WHEN OBJECT IS CREATED
created = False

## TITLE NUMBER< WILL BE USED TO CHANGE THE TITLE BEFORE SAVE
title_number = 1

## HOLD AUTHORIZATION TOKEN
auth_head_tag = {'Authorization':token}

## LOOP WHILE CREATE FAILS
while created == False:

  ## HOLD TITLE + TITLE NUMBER
  title = 'title-testing ' + str(title_number)

  ## HOLD TODO LIST PARAMS
  todo_lists_params = {'todo_list[title]': title, 'todo_list[description]': 'description', 'todo_list[action]': 'run on server'}
  
  ## SEND POST REQUEST TO API TODO LISTS
  r = requests.post((url +'/api/todo_lists'), headers=auth_head_tag, params=todo_lists_params )
  
  ## HOLD JSON RESPONSE IN VARIABLE
  json_response = json.loads(r.text)

  ## INCREASE TITLE NUMBER
  title_number += 1

  ## PRINT THE TITLE
  print(title)

  ## CHECK IF HAS ERRORS IN JSON RESPONSE
  if 'errors' in json_response:

      ## PRINT THE ERRORS
      print('ERROR: ', json_response['errors'], '\n')

      ## SLEEP 2 SECONDS TO AVOID REQUESTO TO GET BLOCKED BY THE SERVER
      time.sleep(2)

  ## IF OK
  else:

      ## PRINT JSON RESPONSE DATA
      print('SUCCESS: ', json_response['data'])

      ## CHANGE CREATED VARIABLE TO TRUE
      created = True

## PRINT JSON RESPONSE AS DATA FRAME
pd.json_normalize(json_response)

title-testing 1
SUCCESS:  {'id': '1', 'type': 'todo-lists', 'attributes': {'title': 'title-testing 1', 'description': 'description', 'mode': 'pending', 'created-at': '2022-04-04T10:50:17.377Z', 'updated-at': '2022-04-04T10:50:17.377Z', 'items-count': 0}}

,data.id,data.type,data.attributes.title,data.attributes.description,data.attributes.mode,data.attributes.created-at,data.attributes.updated-at,data.attributes.items-count
0,1,todo-lists,title-testing 1,description,pending,2022-04-04T10:50:17.377Z,2022-04-04T10:50:17.377Z,0

#### GET /api/view_todo_list/:id - returns a todo list

In [9]:
## HOLD AUTHORIZATION TOKEN HEADER
auth_head_tag = {'Authorization':token}
params = {'id': '1'}
## SEND GET REQUEST WITH AUTHORIZATION TOKEN
r = requests.get((url + '/api/view_todo_list'), headers=auth_head_tag, params=params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON: ', json_response)

## HOLD STATUS CODE IN VARIABLE
status = r.status_code
## WHEN THE REQUEST IS SUCCESSFUL, THE STATUS CODE IS 200

## PRINT STATUS CODE
print('STATUS_CODE: ', status)

## PRITN JSON RESPONSE AS DATA FRAME
pd.json_normalize(json_response)

STATUS_CODE:  200

,data.id,data.type,data.attributes.title,data.attributes.description,data.attributes.mode,data.attributes.created-at,data.attributes.updated-at,data.attributes.items-count
0,1,todo-lists,title-testing 1,description,pending,2022-04-04T10:50:17.377Z,2022-04-04T10:50:17.377Z,0

**EXTRA PYTHON SECTION TO CREATE TODO LIST OBJECTS, IT IS NOT NECESSARY TO THE CHALLENGE**

**CAN USE IT TO TEST RACK CORS AND RACK ATTACK**

In [10]:
## USE MOD VARIABLE AS BASE OF YOUR TITLE
mod = "RECEITA "

## THIS TAG WILL BE ADDED TO THE TITLE EVERY TIME AN ERROR IS FOUND
add_tag = "X"


## THIS FUNCTION USES LOOP TO CREATE TODO REQUESTS IN A GIVEN RANGE
def todo_lists_post_request(auth_head_tag, mod, add_tag, counter):

    ## INIT AN VARIABLE TO HOLD NUMBER OF ERRORS
    errors = 0
    
    ## COUNT OBJECTS CREATED
    objects_created_count = 0
    
    ## COUNTER TO NUMERATE TITLE
    title_numerator = 1

    ## LOOP TO CREATE TODO LISTS
    for i in counter:

        ## HOLD TITLE MOD BASE + TITLE NUMERATOR
        title = (mod + str(title_numerator))

        ## TODO LISTS PARAMS
        todo_lists_params = {'todo_list[title]': title  , 'todo_list[description]': 'description', 'todo_list[action]': 'run on server'}

        ## SEND POST REQUEST TO TODO LISTS
        r = requests.post((url + '/api/todo_lists'), headers=auth_head_tag, params=todo_lists_params)
        ## TIME SLEEP TO AVOID REQUESTS TO BE BLOCKED BY THE SERVER
        time.sleep(2)


        ## CHECK RESPONSE STATUS CODE
        if r.status_code == 422:

            ## IF ERROR IS RAISED ADD TAG TO TITLE BASE MODIFICATOR
            mod += add_tag

            ## INCREASE ERRORS COUNTER
            errors += 1

            ## PRINT ERRORS
            print(errors)

        ## IF THE OBJECT IS CREATED AND STATUS CODE 200
        else:

            ## INCREASE OBJECTS CREATED COUNTER
            objects_created_count += 1

        ## INCREASE TITLE COUNTER
        title_numerator += 1

    ## PRINT OBJECTS CREATED COUNTER
    print('OBJECTS CREATED: ', objects_created_count)

    ## PRINT ERRORS COUNTER
    print('ERRORS: ', errors)
        
## RUN FUNCTION WITH GIVEN ARGS
todo_lists_post_request(auth_head_tag, mod, add_tag, range(20,50))

OBJECTS CREATED:  30
ERRORS:  0

**EXTRA PYTHON SESSION CREATE SOME DEMONSTRATION ITEMS**

In [11]:
## IN THE FIRST PYTHON CELL HAVE A METHOD TO HELP US TO CREATE AND MARK ITEMS
## LET'S CREATE ITEMS FOR THE FIRST, SECOND AND THIRD TODO LIST AND MARK THEM AS EXECUTED OR ARCHIVED
## DEMONSTRATION PURPOSE

lists_ids = ['1', '2', '3']

commands = ['rails new', 'bundle', 'rake db:create db:migrate']

names = ['first', 'second', 'third']

for i in lists_ids:
    for n in range(3):
        json_response = json.loads(post_items(token, i, commands[n], names[n]))
        
        print('CREATED:' , json_response['item']['name'], 'TODO_LIST:' , json_response['item']['todo_list'], 'ID: ', json_response['item']['id'])
        if n == 2:
            marked_response = json.loads(mark_item_as_executed(token, json_response['item']['id']))
            print('MARKED:' , marked_response['data']['attributes']['name'], '\nTODO_LIST:' , marked_response['data']['attributes']['todo-list'], '\nMODE: ', marked_response['data']['attributes']['mode'], '\n')
            
        elif n == 1:
            marked_response = json.loads(mark_item_as_archived(token, json_response['item']['id']))
            print('MARKED:' , marked_response['data']['attributes']['name'], '\nTODO_LIST:' , marked_response['data']['attributes']['todo-list'], '\nMODE: ', marked_response['data']['attributes']['mode'], '\n')

mark_todo_as_done(token, 8)

CREATED: first TODO_LIST: title-testing 1 ID:  1
CREATED: second TODO_LIST: title-testing 1 ID:  2
MARKED: second
TODO_LIST: title-testing 1
MODE:  archived

CREATED: third TODO_LIST: title-testing 1 ID:  3
MARKED: third
TODO_LIST: title-testing 1
MODE:  executed

CREATED: first TODO_LIST: RECEITA 1 ID:  4
CREATED: second TODO_LIST: RECEITA 1 ID:  5
MARKED: second
TODO_LIST: RECEITA 1
MODE:  archived

CREATED: third TODO_LIST: RECEITA 1 ID:  6
MARKED: third
TODO_LIST: RECEITA 1
MODE:  executed

CREATED: first TODO_LIST: RECEITA 2 ID:  7
CREATED: second TODO_LIST: RECEITA 2 ID:  8
MARKED: second
TODO_LIST: RECEITA 2
MODE:  archived

CREATED: third TODO_LIST: RECEITA 2 ID:  9
MARKED: third
TODO_LIST: RECEITA 2
MODE:  executed

'{"data":{"id":"8","type":"todo-lists","attributes":{"title":"RECEITA 7","description":"description","mode":"done","created-at":"2022-04-04T10:50:30.849Z","updated-at":"2022-04-04T10:51:23.338Z","items-count":0}}}'

#### GET /api/todo_lists - returns all todo lists with serializer and pagination

All Todo List object is inside the data array

Simple wrap the Todo List object with the serializer

Pagy add pagination to the response headers

Print headers to see what pagy gem is doing

In [12]:
## AUTH TOKEN HEADER
auth_head_tag = {'Authorization':token}

## SEND REQUEST WITH AUTH TOKEN
r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag)


## PRINT INFO 
# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code) 
# print( 'BODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code) 

## HOLD JSON RESPONSE IN VARIALBE
json_response = json.loads(r.text)


## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']

## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']


## PRINT CURRENT AND TOTAL PAGES NUMBER
print('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')
            

## HOLD JSON OBJECTS IN VARIABLE
json_objects = json_response['data']

## PRINT HEADERS
# print ('HEADERS: ', r.headers, '\n')

## PRINT OBJECTS
# for js_object in json_objects:
#     print('JSON_OBJECT: ', js_object, '\n')

## PRINT OBJECTS AS DATA FRAME
pd.json_normalize(json_objects)

CURRENT PAGE:  1

TOTAL PAGES:  4

,id,type,attributes.title,attributes.description,attributes.mode,attributes.created-at,attributes.updated-at,attributes.items-count
0,1,todo-lists,title-testing 1,description,initiated,2022-04-04T10:50:17.377Z,2022-04-04T10:51:21.234Z,3
1,2,todo-lists,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,3
2,3,todo-lists,RECEITA 2,description,initiated,2022-04-04T10:50:20.374Z,2022-04-04T10:51:22.524Z,3
3,4,todo-lists,RECEITA 3,description,pending,2022-04-04T10:50:22.451Z,2022-04-04T10:50:22.451Z,0
4,5,todo-lists,RECEITA 4,description,pending,2022-04-04T10:50:24.559Z,2022-04-04T10:50:24.559Z,0
5,6,todo-lists,RECEITA 5,description,pending,2022-04-04T10:50:26.651Z,2022-04-04T10:50:26.651Z,0
6,7,todo-lists,RECEITA 6,description,pending,2022-04-04T10:50:28.778Z,2022-04-04T10:50:28.778Z,0
7,8,todo-lists,RECEITA 7,description,done,2022-04-04T10:50:30.849Z,2022-04-04T10:51:23.338Z,0
8,9,todo-lists,RECEITA 8,description,pending,2022-04-04T10:50:32.909Z,2022-04-04T10:50:32.909Z,0
9,10,todo-lists,RECEITA 9,description,pending,2022-04-04T10:50:34.982Z,2022-04-04T10:50:34.982Z,0

#### GET /api/todo_lists?page=PAGENUMBER - returns a todo lists list with pagination

Utilize the page number to get the next page of todo lists

In [13]:
## HOLD PAGE NUMBER PARAMETER IN VARIABLE
page_params = {'page': '1'}

## SEND GET REQUEST WITH PAGE NUMBER PARAMETER
r = requests.get((url +  '/api/todo_lists'), headers=auth_head_tag, params=page_params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']
## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']
## PRINT CURRENT AND TOTAL PAGES NUMBER
print('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')
## HOLD JSON OBJECTS IN VARIABLE            
json_objects = json_response['data']


## PRINT HEADERS
# print ('HEADERS: ', r.headers, '\n')

## PRINT OBJECTS
# for js_object in json_objects:
#     print('JSON_OBJECT: ', js_object, '\n')

## PRINT OBJECTS AS DATA FRAME
pd.json_normalize(json_response['data'])

CURRENT PAGE:  1

TOTAL PAGES:  4

,id,type,attributes.title,attributes.description,attributes.mode,attributes.created-at,attributes.updated-at,attributes.items-count
0,1,todo-lists,title-testing 1,description,initiated,2022-04-04T10:50:17.377Z,2022-04-04T10:51:21.234Z,3
1,2,todo-lists,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,3
2,3,todo-lists,RECEITA 2,description,initiated,2022-04-04T10:50:20.374Z,2022-04-04T10:51:22.524Z,3
3,4,todo-lists,RECEITA 3,description,pending,2022-04-04T10:50:22.451Z,2022-04-04T10:50:22.451Z,0
4,5,todo-lists,RECEITA 4,description,pending,2022-04-04T10:50:24.559Z,2022-04-04T10:50:24.559Z,0
5,6,todo-lists,RECEITA 5,description,pending,2022-04-04T10:50:26.651Z,2022-04-04T10:50:26.651Z,0
6,7,todo-lists,RECEITA 6,description,pending,2022-04-04T10:50:28.778Z,2022-04-04T10:50:28.778Z,0
7,8,todo-lists,RECEITA 7,description,done,2022-04-04T10:50:30.849Z,2022-04-04T10:51:23.338Z,0
8,9,todo-lists,RECEITA 8,description,pending,2022-04-04T10:50:32.909Z,2022-04-04T10:50:32.909Z,0
9,10,todo-lists,RECEITA 9,description,pending,2022-04-04T10:50:34.982Z,2022-04-04T10:50:34.982Z,0

##### GET /api/items?page=PAGENUMBER&todo_list_id=ID - returns a list of items with pagination

In [14]:
## HOLD PAGE NUMBEBER AND TODO LIST ID PARAMETERS IN VARIABLES
page_with_todo_list_params = {'page': '1', 'todo_list_id': '2'}

## SEND GET REQUEST WITH PAGE NUMBER AND TODO LIST ID PARAMETERS
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)


## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_list_object = json_response['todo_list']

## HOLD ITEMS OBJECTS IN VARIABLE
json_items_objects = json_response['items']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']

## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']

## PRINT CURRENT AND TOTAL PAGES NUMBER
print('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')


## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            
## PRINT TODO LIST OBJECT AS DATA FRAME
pd.json_normalize(json_todo_list_object)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,2,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,3

In [15]:
## PRINT ITEMS OBJECTS AS DATA FRAME
pd.json_normalize(json_items_objects)

,id,name,action,mode,created_at,updated_at,todo_list
0,4,first,rails new,pending,2022-04-04T10:51:21.943Z,2022-04-04T10:51:21.943Z,RECEITA 1
1,6,third,rake db:create db:migrate,executed,2022-04-04T10:51:22.265Z,2022-04-04T10:51:22.391Z,RECEITA 1

#### POST /api/items - creates a new item in a todo list

**ACCEPT PARAMS:**

    * todo_list_id
    * action
    * name

**SETTED AUTOMATICALLY:**

    * mode
    * created_at
    * updated_at

**DEFAULT VALUES:**

    * mode = pending
    * created_at = updated_at = current time

**EXAMPLE PARAMS:**
    
        { "item": 
            { "todo_list_id": "",
              "action": "",
              "name": "",
            }
        }

**URL PARAMS EXAMPLE:**
?item[todo_list_id]=VALUE&item[action]=VALUE&item[name]=VALUE

In [16]:
## HOLD ITEM PARAMETERS IN VARIABLE
item_params = {'item[todo_list_id]': '2', 'item[action]': 'run on server','item[name]': 'item'}

## SEND POST REQUEST WITH ITEM PARAMETERS
r = requests.post((url + '/api/items'), headers=auth_head_tag, params=item_params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## PRINT ITEM AS DATA FRAME
pd.json_normalize(json_response['item'])

,id,name,action,mode,created_at,updated_at,todo_list
0,10,item,run on server,pending,2022-04-04T10:51:24.916Z,2022-04-04T10:51:24.916Z,RECEITA 1

### GET /api/view_item - returns a specific item with given id
Access object in view_item show page

It change object mode to read

You can set params with "true" value to change it to other modes (**read is setted by default if u access this endpoint**)

**Available params:**
    * executed
    * archived

When mode is archived, the item is not shown in the common lists (**only can be accessed if a list of archived items is requested**)

In [17]:
## HOLD ITEM ID PARAMETER IN VARIABLE
item_id_param = {'id': '1'}

## SEND GET REQUEST WITH ITEM ID PARAMETER
r = requests.get((url + '/api/view_item/'), headers=auth_head_tag, params=item_id_param)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## CHECK IF ITEM EXISTS
if 'data' in json_response:
    json_objects = json_response['data']
else:
    json_objects = json_response

## PRINT ITEM AS DATA FRAME
pd.json_normalize(json_objects)

,id,type,attributes.name,attributes.action,attributes.mode,attributes.created-at,attributes.updated-at,attributes.todo-list
0,1,items,first,rails new,read,2022-04-04T10:51:21.174Z,2022-04-04T10:51:25.183Z,title-testing 1

#### GET /api/items/:id&:executed - updates an item with given id and executed status

In [18]:
## HOLD ITEM ID AND EXECUTED BOOLEAN PARAMETERS IN VARIABLE
params = {'id': '1', 'executed': 'true'}

## SEND GET REQUEST WITH ITEM ID AND EXECUTED BOOLEAN PARAMETERS
r = requests.get((url + '/api/view_item/'), headers=auth_head_tag, params=params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## CHECK IF ITEM EXISTS
if 'data' in json_response:
    json_objects = json_response['data']
else:
    json_objects = json_response

## PRINT ITEM AS DATA FRAME
pd.json_normalize(json_objects)

,id,type,attributes.name,attributes.action,attributes.mode,attributes.created-at,attributes.updated-at,attributes.todo-list
0,1,items,first,rails new,executed,2022-04-04T10:51:21.174Z,2022-04-04T10:51:25.550Z,title-testing 1

#### GET /api/items/:id&:archived - updates an item with given id and archived status

In [19]:
## HOLD ITEM ID AND ACHIVED BOOLEAN PARAMETERS IN VARIABLE
params = {'id': '1', 'archived': 'true'}

## SEND GET REQUEST WITH ITEM ID AND ACHIVED BOOLEAN PARAMETERS
r = requests.get((url + '/api/view_item/'), headers=auth_head_tag, params=params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## CHECK IF ITEM EXISTS
if 'data' in json_response:
    json_objects = json_response['data']
else:
    json_objects = json_response

## PRINT ITEM AS DATA FRAME
pd.json_normalize(json_objects)

,id,type,attributes.name,attributes.action,attributes.mode,attributes.created-at,attributes.updated-at,attributes.todo-list
0,1,items,first,rails new,archived,2022-04-04T10:51:21.174Z,2022-04-04T10:51:25.987Z,title-testing 1

#### GET /api/items - returns all items with pagination and filter - example: object sorted by enum mode (asc)


 Utilize the page number to get the next page of items

 mode is defined in todo list and item models, it can be:

 [:pending, :read, :executed, :archived] for items

 [:pending, :initiated, :done] for todo lists

In [20]:
## HOLD PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'todo_list_id': '2', 'filter': 'mode_asc'}

## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_list_object = json_response['todo_list']

## HOLD ITEMS OBJECTS IN VARIABLE
json_items_objects = json_response['items']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']

## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']

## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')
            

## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            

## PRINT TODO LIST OBJECT AS DATA FRAME
pd.json_normalize(json_todo_list_object)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,2,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,4

In [21]:
## PRINT ITEMS OBJECTS AS DATA FRAME
pd.json_normalize(json_items_objects)

,id,name,action,mode,created_at,updated_at,todo_list
0,4,first,rails new,pending,2022-04-04T10:51:21.943Z,2022-04-04T10:51:21.943Z,RECEITA 1
1,10,item,run on server,pending,2022-04-04T10:51:24.916Z,2022-04-04T10:51:24.916Z,RECEITA 1
2,6,third,rake db:create db:migrate,executed,2022-04-04T10:51:22.265Z,2022-04-04T10:51:22.391Z,RECEITA 1

#### GET /api/items?page=PAGENUMBER&filter=MODE - returns a list of items with pagination and filter - example: object sorted by enum mode (desc)

Utilize the page number to get the next page of items

mode is defined in todo list and item models, it can be:

[:pending, :read, :executed, :archived] for items

[:pending, :initiated, :done] for todo lists

In [22]:
## HOLD PAGE NUMBER, TODO LIST ID AND MODE PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'todo_list_id': '4', 'filter': 'mode_desc'}

## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_list_object = json_response['todo_list']

## HOLD ITEMS OBJECTS IN VARIABLE
json_items_objects = json_response['items']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']

## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']

## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')

            
## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            

## PRINT TODO LIST OBJECT AS DATA FRAME
pd.json_normalize(json_todo_list_object)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,4,RECEITA 3,description,pending,2022-04-04T10:50:22.451Z,2022-04-04T10:50:22.451Z,0

In [23]:
pd.json_normalize(json_items_objects)

Empty DataFrame
Columns: []
Index: []

##### GET /api/items?page=PAGENUMBER&filter=mode_pending_only&todo_list_id=ID - returns a list of items with pagination and filter - example: only objects in pending mode

Utilize the page number to get the next page of items

mode is defined in todo list and item models, it can be:

[:pending, :read, :executed, :archived] for items

[:pending, :initiated, :done] for todo lists

In [24]:
## HOLD PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'todo_list_id': '2', 'filter': 'mode_pending_only'}


## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_list_object = json_response['todo_list']
## HOLD ITEMS OBJECTS IN VARIABLE
json_items_objects = json_response['items']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']
## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']
            
## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')

## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

            
## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            
## PRINT TODO LIST OBJECT AS DATA FRAME'
pd.json_normalize(json_todo_list_object)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,2,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,4

In [25]:
## PRINT ITEMS OBJECTS AS DATA FRAME
pd.json_normalize(json_items_objects)

,id,name,action,mode,created_at,updated_at,todo_list
0,4,first,rails new,pending,2022-04-04T10:51:21.943Z,2022-04-04T10:51:21.943Z,RECEITA 1
1,10,item,run on server,pending,2022-04-04T10:51:24.916Z,2022-04-04T10:51:24.916Z,RECEITA 1

##### GET /api/items?page=PAGENUMBER&filter=mode_read_only&todo_list_id=ID - returns a list of items with pagination and filter - example: only objects in read mode

Utilize the page number to get the next page of items

mode is defined in todo list and item models, it can be:

[:pending, :read, :executed, :archived] for items

[:pending, :initiated, :done] for todo lists

In [26]:
## HOLD PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'todo_list_id': '2', 'filter': 'mode_read_only'}


## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_list_object = json_response['todo_list']
## HOLD ITEMS OBJECTS IN VARIABLE
json_items_objects = json_response['items']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']
## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']
            
## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')

## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

            
## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            
## PRINT TODO LIST OBJECT AS DATA FRAME'
pd.json_normalize(json_todo_list_object)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,2,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,4

In [27]:
## PRINT ITEMS OBJECTS AS DATA FRAME
pd.json_normalize(json_items_objects)

Empty DataFrame
Columns: []
Index: []

##### GET /api/items?page=PAGENUMBER&filter=mode_executed_only&todo_list_id=ID - returns a list of items with pagination and filter - example: only objects in executed mode

Utilize the page number to get the next page of items

mode is defined in todo list and item models, it can be:

[:pending, :read, :executed, :archived] for items

[:pending, :initiated, :done] for todo lists

In [28]:
## HOLD PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'todo_list_id': '2', 'filter': 'mode_executed_only'}


## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_list_object = json_response['todo_list']
## HOLD ITEMS OBJECTS IN VARIABLE
json_items_objects = json_response['items']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']
## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']
            
## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')

## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

            
## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            
## PRINT TODO LIST OBJECT AS DATA FRAME'
pd.json_normalize(json_todo_list_object)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,2,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,4

In [29]:
## PRINT ITEMS OBJECTS AS DATA FRAME
pd.json_normalize(json_items_objects)

,id,name,action,mode,created_at,updated_at,todo_list
0,6,third,rake db:create db:migrate,executed,2022-04-04T10:51:22.265Z,2022-04-04T10:51:22.391Z,RECEITA 1

#### GET /apiview_todo_list/:id&:initiated - updates an todo list with given id and initiated status mode

In [30]:
## HOLD AUTHORIZATION TOKEN HEADER
auth_head_tag = {'Authorization':token}
params = {'id': '5', 'initiated': 'true'}
## SEND GET REQUEST WITH AUTHORIZATION TOKEN
r = requests.get((url + '/api/view_todo_list'), headers=auth_head_tag, params=params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON: ', json_response)

## HOLD STATUS CODE IN VARIABLE
status = r.status_code
## WHEN THE REQUEST IS SUCCESSFUL, THE STATUS CODE IS 200

## PRINT STATUS CODE
print('STATUS_CODE: ', status)

## PRITN JSON RESPONSE AS DATA FRAME
pd.json_normalize(json_response)

STATUS_CODE:  500

,status,error,exception,traces.Application Trace,traces.Framework Trace,traces.Full Trace
0,500,Internal Server Error,#<ArgumentError: 'intiated' is not a valid mode>,"[{'exception_object_id': 28360, 'id': 22, 'tra...","[{'exception_object_id': 28360, 'id': 0, 'trac...","[{'exception_object_id': 28360, 'id': 0, 'trac..."

#### GET /apiview_todo_list/:id&:done - updates an todo list with given id and done status mode

In [31]:
## HOLD AUTHORIZATION TOKEN HEADER
auth_head_tag = {'Authorization':token}
params = {'id': '6', 'done': 'true'}
## SEND GET REQUEST WITH AUTHORIZATION TOKEN
r = requests.get((url + '/api/view_todo_list'), headers=auth_head_tag, params=params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON: ', json_response)

## HOLD STATUS CODE IN VARIABLE
status = r.status_code
## WHEN THE REQUEST IS SUCCESSFUL, THE STATUS CODE IS 200

## PRINT STATUS CODE
print('STATUS_CODE: ', status)

## PRITN JSON RESPONSE AS DATA FRAME
pd.json_normalize(json_response)

STATUS_CODE:  200

,data.id,data.type,data.attributes.title,data.attributes.description,data.attributes.mode,data.attributes.created-at,data.attributes.updated-at,data.attributes.items-count
0,6,todo-lists,RECEITA 5,description,done,2022-04-04T10:50:26.651Z,2022-04-04T10:51:30.126Z,0

##### GET /api/todo_lists?page=PAGENUMBER&filter=mode_pending_only - returns a list of items with pagination and filter - example: only objects in pending mode

In [32]:
## HOLD PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'filter': 'mode_pending_only'}


## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS
r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_lists_objects = json_response['data']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']
## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']
            
## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')

## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

            
## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            
## PRINT TODO LIST OBJECT AS DATA FRAME'
pd.json_normalize(json_todo_lists_objects)

CURRENT PAGE:  1

TOTAL PAGES:  3

,id,type,attributes.title,attributes.description,attributes.mode,attributes.created-at,attributes.updated-at,attributes.items-count
0,4,todo-lists,RECEITA 3,description,pending,2022-04-04T10:50:22.451Z,2022-04-04T10:50:22.451Z,0
1,5,todo-lists,RECEITA 4,description,pending,2022-04-04T10:50:24.559Z,2022-04-04T10:50:24.559Z,0
2,7,todo-lists,RECEITA 6,description,pending,2022-04-04T10:50:28.778Z,2022-04-04T10:50:28.778Z,0
3,9,todo-lists,RECEITA 8,description,pending,2022-04-04T10:50:32.909Z,2022-04-04T10:50:32.909Z,0
4,10,todo-lists,RECEITA 9,description,pending,2022-04-04T10:50:34.982Z,2022-04-04T10:50:34.982Z,0
5,11,todo-lists,RECEITA 10,description,pending,2022-04-04T10:50:37.053Z,2022-04-04T10:50:37.053Z,0
6,12,todo-lists,RECEITA 11,description,pending,2022-04-04T10:50:39.136Z,2022-04-04T10:50:39.136Z,0
7,13,todo-lists,RECEITA 12,description,pending,2022-04-04T10:50:41.202Z,2022-04-04T10:50:41.202Z,0
8,14,todo-lists,RECEITA 13,description,pending,2022-04-04T10:50:43.327Z,2022-04-04T10:50:43.327Z,0
9,15,todo-lists,RECEITA 14,description,pending,2022-04-04T10:50:45.469Z,2022-04-04T10:50:45.469Z,0

##### GET /api/todo_lists?page=PAGENUMBER&filter=mode_initiated_only - returns a list of items with pagination and filter - example: only objects in initiated mode

In [33]:
## HOLD PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'filter': 'mode_initiated_only'}


## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS
r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_lists_objects = json_response['data']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']
## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']
            
## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')

## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

            
## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            
## PRINT TODO LIST OBJECT AS DATA FRAME'
pd.json_normalize(json_todo_lists_objects)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,type,attributes.title,attributes.description,attributes.mode,attributes.created-at,attributes.updated-at,attributes.items-count
0,1,todo-lists,title-testing 1,description,initiated,2022-04-04T10:50:17.377Z,2022-04-04T10:51:21.234Z,3
1,2,todo-lists,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,4
2,3,todo-lists,RECEITA 2,description,initiated,2022-04-04T10:50:20.374Z,2022-04-04T10:51:22.524Z,3

##### GET /api/todo_lists?page=PAGENUMBER&filter=mode_done_only - returns a list of items with pagination and filter - example: only objects in done mode

In [34]:
## HOLD PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'filter': 'mode_done_only'}


## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER PARAMETERS
r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_lists_objects = json_response['data']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']
## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']
            
## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')

## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

            
## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            
## PRINT TODO LIST OBJECT AS DATA FRAME'
pd.json_normalize(json_todo_lists_objects)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,type,attributes.title,attributes.description,attributes.mode,attributes.created-at,attributes.updated-at,attributes.items-count
0,6,todo-lists,RECEITA 5,description,done,2022-04-04T10:50:26.651Z,2022-04-04T10:51:30.126Z,0
1,8,todo-lists,RECEITA 7,description,done,2022-04-04T10:50:30.849Z,2022-04-04T10:51:23.338Z,0

##### GET /api/items?page=PAGENUMBER&filter_factor&todo_list_id=ID - returns a list of items with pagination and filter - example: object sorted by selected factor

**HOW TO FILTER WITH FACTOR?**

Items and todo lists can be filtered by mode order in asc, desc like already done in the previous examples
But it can be filtered in different orders by factor


**COMMOM ORDERS:**

    common_order = [:pending, :read, :executed, :archived]
    its_like = [0, 1, 2, 3]

    asc = comom_order
    desc = [3 ,2 ,1 ,0]


**ITEMS FACTORED ORDERS(MATRIX):**

    0 =  [1, 2, 3, 0] 
    1 =  [2, 3, 0, 1]
    2 =  [3, 0, 1, 2]
    3 =  [0, 1, 2, 3]
    4 =  [1, 3, 2, 0]
    5 =  [2, 1, 0, 3]
    6 =  [3, 2, 1, 0]
    7 =  [0, 3, 2, 1]
    8 =  [1, 0, 3, 2]
    9 =  [2, 0, 1, 3]
    10 = [3, 1, 0, 2]
    11 = [0, 2, 1, 3]
    12 = [1, 3, 0, 2]
    13 = [2, 3, 1, 0]
    14 = [3, 0, 2, 1]
    15 = [0, 1, 3, 2]
    16 = [1, 2, 0, 3]
    17 = [2, 1, 3, 0]
    18 = [3, 2, 0, 1]
    19 = [0, 3, 1, 2]
    20 = [1, 0, 2, 3]
    21 = [2, 0, 3, 1]
    22 = [3, 1, 2, 0]
    23 = [0, 2, 3, 1]




**Utilize matrix order number in params**

**EXAMPLE PARAMS(REMEMBER, ONLY TODO LIST ID IS REQUIRED TO ACCESS THE LIST EVER):**

    { page: 1,
      filter_factor: 0,
      todo_list_id: 1
    }

In [42]:
## HOLD PAGE NUMBER, TODO LIST ID AND FILTER FACTOR ORDER NUMBER PARAMETERS IN VARIABLE
page_with_todo_list_params = {'page': '1', 'todo_list_id': '1', 'filter_factor': '2'}

## SEND GET REQUEST WITH PAGE NUMBER, TODO LIST ID AND FILTER FACTOR ORDER NUMBER PARAMETERS
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## HOLD TODO LIST OBJECT IN VARIABLE
json_todo_list_object = json_response['todo_list']
## HOLD ITEMS OBJECTS IN VARIABLE
json_items_objects = json_response['items']

## HOLD TOTAL COUNT OF PAGES
total_pages = r.headers['Total-Pages']
## HOLD CURRENT PAGE NUMBER
current_page = r.headers['Current-Page']


## PRINT CURRENT AND TOTAL PAGES NUMBER
print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')

## PRINT TODO LIST OBJECT
# print("TODO LIST: ", json_todo_list_object, '\n')

            
## PRINT ITEMS OBJECTS
# for item in json_items_objects:
#     print('ITEM: ', item, '\n')

## PRINT TODO LIST OBJECT AS DATA FRAME'
pd.json_normalize(json_todo_list_object)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,1,title-testing 1,description,initiated,2022-04-04T10:50:17.377Z,2022-04-04T10:51:21.234Z,3

In [43]:
## PRINT ITEMS OBJECTS AS DATA FRAME
pd.json_normalize(json_items_objects)

,id,name,action,mode,created_at,updated_at,todo_list
0,1,first,rails new,archived,2022-04-04T10:51:21.174Z,2022-04-04T10:51:25.987Z,title-testing 1
1,2,second,bundle,archived,2022-04-04T10:51:21.571Z,2022-04-04T10:51:21.685Z,title-testing 1

**TODOS COMMOM ORDERS:**

    common_order = [:pending, :initiatied, :done]
    its_like = [0, 1, 2]

    asc = comom_order
    desc = [2 ,1 ,0]


**TODO LISTS FACTORED ORDERS(MATRIX):**

    0 = [0, 1, 2]
    1 = [1, 2, 0]
    2 = [2, 0, 1]
    3 = [0, 2, 1]
    4 = [1, 0, 2]
    5 = [2, 1, 0]

In [37]:
## HOLD PAGE NUMBER AND FILTER FACTOR ORDER NUMBER PARAMETERS IN VARIABLE
params = { 'page': 1, 'filter_factor': 1 }

## SEND GET REQUEST WITH PAGE NUMBER AND FILTER FACTOR ORDER NUMBER PARAMETERS
r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag, params=params)

## HOLD JSON RESPONSE DATA IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE DATA AS DATA FRAME
pd.json_normalize(json_response['data'])

,id,type,attributes.title,attributes.description,attributes.mode,attributes.created-at,attributes.updated-at,attributes.items-count
0,3,todo-lists,RECEITA 2,description,initiated,2022-04-04T10:50:20.374Z,2022-04-04T10:51:22.524Z,3
1,1,todo-lists,title-testing 1,description,initiated,2022-04-04T10:50:17.377Z,2022-04-04T10:51:21.234Z,3
2,2,todo-lists,RECEITA 1,description,initiated,2022-04-04T10:50:18.294Z,2022-04-04T10:51:21.994Z,4
3,6,todo-lists,RECEITA 5,description,done,2022-04-04T10:50:26.651Z,2022-04-04T10:51:30.126Z,0
4,8,todo-lists,RECEITA 7,description,done,2022-04-04T10:50:30.849Z,2022-04-04T10:51:23.338Z,0
5,7,todo-lists,RECEITA 6,description,pending,2022-04-04T10:50:28.778Z,2022-04-04T10:50:28.778Z,0
6,10,todo-lists,RECEITA 9,description,pending,2022-04-04T10:50:34.982Z,2022-04-04T10:50:34.982Z,0
7,9,todo-lists,RECEITA 8,description,pending,2022-04-04T10:50:32.909Z,2022-04-04T10:50:32.909Z,0
8,5,todo-lists,RECEITA 4,description,pending,2022-04-04T10:50:24.559Z,2022-04-04T10:50:24.559Z,0
9,4,todo-lists,RECEITA 3,description,pending,2022-04-04T10:50:22.451Z,2022-04-04T10:50:22.451Z,0

##### GET /api/delete_todo_list - deletes a todo list with given id

In [38]:
## HOLD TODO LIST ID PARAMETER IN VARIABLE
params = {'id': '4'}

## SEND GET REQUEST WITH TODO LIST ID PARAMETER
r = requests.get((url + '/api/delete_todo_list'), headers=auth_head_tag, params=params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## PRINT JSON RESPONSE AS DATA FRAME
pd.json_normalize(json_response)

                          message
0  Todo list deleted successfully

##### GET /api/remove_item - deletes an item with given id

In [39]:
## HOLD ITEM ID PARAMETER IN VARIABLE
params = {'id': '8'}

## SEND GET REQUEST WITH ITEM ID PARAMETER
r = requests.get((url + '/api/remove_item'), headers=auth_head_tag, params=params)

## HOLD JSON RESPONSE IN VARIABLE
json_response = json.loads(r.text)

## PRINT JSON RESPONSE
# print('JSON_RESPONSE: ', json_response, '\n')

## PRINT JSON RESPONSE AS DATA FRAME
pd.json_normalize(json_response)

        message
0  Item deleted